.travis.yml, tox.ini
Update versions, now we have Conan 1.11
=> Roll versions forward

README.md, appveyor.yml
py34 is failing, related to https://github.com/conan-io/conan/issues/3434
=> Add Appveyor (and badges)

README.md
First example of documentation, when there are more _hooks_ we can consider moving it inside a dedicated folder.
=> Document hooks (first in the README)

.gitignore, .travis.yml, .travis/requirements_travis.txt, appveyor.yml, tests/requirements_test.txt, tests/utils/capabilities.py, tests/utils/test_cases/conan_client.py, tox.ini
Tox is running the test-suite, so it should be that utility the one that installs the requirements. Also, I'm adding a couple of utilities that I will be using in my next PR (please, be gentle with those additions)
=> Enhancements to test suite

.travis.yml, appveyor.yml, tox.ini
=> Remove Conan 1.9, add Conan 1.12 as first class citizen

README.md, hooks/conan-center.py, tests/test_hooks/test_conan-center.py, tests/utils/test_cases/conan_client.py
fixes #37 
- Review issues of the hook
- Added basic tests
- Included documentation
=>  Review conan-center hook

README.md, hooks/bintray_update.py
Hi!
This PR renames the Bintray account variables, like username and password.
fixes #36 
/cc @lasote
=> #36 Bintray hooks should use Bintray variables

hooks/conan-center_reviewer.py
=> - add cc to C++ extentions

.travis.yml, appveyor.yml, tox.ini
=> Test hook with latest stable version (#58)

hooks/conan-center_reviewer.py
=> #50 Exclude installer from conan-center_review

.travis.yml, appveyor.yml, tox.ini
Update testing versions to `v15.x`, `v14.x`, `v13.x`.
=> Update testing versions

tests/requirements_test.txt
Declare some dependencies explicitly
=> Fix appveyor CI

.travis.yml, appveyor.yml, tox.ini
From time to time we need to update the versions this repo is using to test
=> Up Conan versions

hooks/conan-center.py
Signed-off-by: Uilian Ries <uilianries@gmail.com>
=> Fix typo for build dirs

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
=> Fix weak detection of fPIC option

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
Reverting this as explained in #111
=> [conan center] Revert linter hook

.travis.yml, .travis/before_install.sh
closes https://github.com/conan-io/hooks/pull/137
=> [CI] Investigate OpenSSL issue (MacOS - py2)

hooks/conan-center.py, tests/test_hooks/conan-center/test_conandata.py
=> Relax immutable source hook

.travis.yml, appveyor.yml, tox.ini
=> #146 Fix py2 support

.travis.yml, appveyor.yml, tox.ini
=> Update Conan versions for CI jobs

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
Related to https://github.com/conan-io/conan-center-index/pull/812/files#r383513483
/cc @SSE4
=> cmake minimum version must be at the beginning

hooks/conan-center.py
also output a message when running on unknown OS
=> FreeBSD support for conan-center hook

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
This PR comes from https://github.com/conan-io/conan-center-index/pull/1179#issuecomment-603577390
=> Allow RunEnvironment for test_package

.travis.yml, appveyor.yml, tox.ini
- Now Conan 1.25.0 is the current version to be tested.
=> Update Conan version for tests

hooks/conan-center.py, tests/test_hooks/conan-center/test_final_newline.py
Ignore files in `test_package/build` while testing missing final endline
=> Ignore files in build folder while testing missing endline

hooks/conan-center.py
closes: #193 
disabled:
- [IMMUTABLE SOURCES (KB-H010)]
- [PACKAGE LICENSE (KB-H012)]
- [MATCHING CONFIGURATION (KB-H014)]
=> do not run certain checks for system packages

.ci/last_conan_version.py, .travis.yml, .travis/requirements_travis.txt, appveyor.yml, tox.ini
Same PR as https://github.com/conan-io/examples/pull/65
=> Automatically roll releases

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
After https://github.com/conan-io/conan-center-index/pull/1938
=> Header only because settings are cleared

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
=> Enforce usage of topics attribute

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
This hooks is the answer for https://github.com/conan-io/conan-center-index/issues/2184
Docs: https://github.com/conan-io/conan-center-index/pull/2284
- CMake +3 is mandatory for test_package/CMakeLists.txt
- If CXX_STANDARD or CMAKE_CXX_STANDARD is declared, CMake +3 is mandatory
closes https://github.com/conan-io/conan-center-index/issues/2184
=> Check minimal CMake version for test pkg (KB-H048)

hooks/binary_linter.py
=> binary linter improvements

hooks/conan-center.py
=> Link to documentation in the docs folder

hooks/conan-center.py
Check that 'default_options' is a dictionary (if present)
Docs: https://github.com/conan-io/conan-center-index/pull/2626
=> Use a dictionary to declare default_options

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
fixes https://github.com/conan-io/hooks/issues/241
=> KB-H048 should accept quotes

hooks/conan-center.py, tests/test_hooks/conan-center/test_cmake_bad_files.py
=> #238 Skip builddirs from components

hooks/conan-center.py
Required by https://github.com/conan-io/conan-center-index/pull/2302
/cc @madebr
=> Ignore gnu-config for KB-H014

hooks/conan-center.py
this can be merged after https://github.com/conan-io/conan-center-index/pull/3341 is merged
=> remove glib from KB-H050 exceptions

hooks/conan-center.py
conans.model.Generator is explicitly documented in https://docs.conan.io/en/latest/howtos/custom_generators.html
see https://github.com/conan-io/conan-center-index/pull/1759#issuecomment-711129395
=> KB-H053: allow custom generators

hooks/members_typo_checker.py
=> Add python_requires_extend to members_typo_checker

hooks/conan-center.py, tests/test_hooks/conan-center/test_conandata.py
=> [conan center] allow different sources per config

hooks/conan-center.py
This is a proposition, preventing problems like https://github.com/conan-io/conan-center-index/pull/4610 from happening.
This hook checks 3 things:
1. if some libdir contain no library files at all (warning)
2. if some libdir contain libraries, but none of these are declared in the libs attribute (warning)
3. if some libraries declared in libs attribute cannot be found in the associated libdirs (error)
If you are ok with this idea, I'll add unit tests and documentation
=> check the existence of declared libraries

hooks/conan-center.py
Please see https://github.com/conan-io/conan-center-index/pull/4491 why
this is required.
=> Add KB-H013 zulu-openjdk exception

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
Related to https://github.com/conan-io/hooks/pull/283 and #282
As commented by @ericLemanissier and @SSE4, #282 only covers basic cases, but a recipe can use different combinations of spaces and tabs.
=> Accepts tabs and multiple spaces for name attr

hooks/conan-center.py
Required by https://github.com/conan-io/conan-center-index/pull/4327
=> Update mingw package name

tests/requirements_test.txt, tests/test_hooks/test_spdx_checker.py
So far we don't test SPDX hook
Requires #290 
/cc @theirix
=> Add SPDX tests

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
First, we need to merge follow PRs, fixing Public Domain:
Related to: https://github.com/conan-io/conan-center-index/pull/5287
=> Add rule for public domain

hooks/conan-center.py
Needed for https://github.com/conan-io/conan-center-index/pull/5796
=> [KB-H013] Add ICU 'config' folder to whitelist

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
Hello! This PR implements #298 
Any reserved character won't be allowed anymore. The error message will list the file name and ask for renaming.
closes https://github.com/conan-io/hooks/issues/298
/cc @madebr
=> KB-H058 Disallowed characters

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
Nothing new, I just copied that instruction from Hook 009. I remember we already had this bug in the past with other hooks, my mistake didn't consider that case.
fixes #315
=> KB-H060 Discard temp folders

hooks/conan-center.py
Required for this PR: https://github.com/conan-io/conan-center-index/pull/6390
=> KB014 - add exception for xorg-macros

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
=> [conan-centre] prefer tools.cross_building(self) over tools.cross_building(self.settings) 

hooks/conan-center.py
For https://github.com/conan-io/conan-center-index/pull/6720#issuecomment-895360017
=> conan-center: order KB-H014 exceptions alphabetically + add xorg-cf-files

README.md
=> Fix broken link related to Conan Center contribution

hooks/conan-center.py
https://github.com/conan-io/conan-center-index/pull/6888#issuecomment-900077589
=> Ignore "KB-H021" for android-ndk.

hooks/conan-center.py
=> KB-H014: allow wayland-protocols

hooks/conan-center.py
This is needed for https://github.com/conan-io/conan-center-index/pull/6887
=> KB-H050: add onetbb to the allowlist

hooks/conan-center.py
For https://github.com/conan-io/conan-center-index/pull/7155
=> Add gtk-doc-stub to KB-H014 allowlist

.ci/Jenkinsfile, hooks/recipe_linter.py, tests/requirements_test.txt, tox.ini
* Fix dependency for `pylint`. Version `2.11` changes the output, something for another PR
* Stop using py35, move to py36
=> [test] Investigate failure in CI

hooks/conan-center.py
For https://github.com/conan-io/conan-center-index/pull/6163
=> Skip emsdk from KB-H021

hooks/binary_linter.py
=> - update binary linter for VS2022

hooks/conan-center.py
related to https://github.com/conan-io/conan-center-index/pull/8349
are we ok with the name of the package ?
=> KB-H013: add exception for mingw-builds

hooks/conan-center.py
=> - [conan-center] compatibility with develop2 (alpha)

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py, tests/test_hooks/conan-center/test_library_install.py
=> Improved KB-H054 message

hooks/conan-center.py, tests/test_hooks/conan-center/test_library_install.py
Context: https://cpplang.slack.com/archives/C41CWV9HA/p1645093283027459
=> KB-H054: find libraries by full file name too

.ci/Jenkinsfile, .ci/generate_env_macos.sh, .ci/requirements_macos.txt, .ci/run_tox.sh
=> - enable mac CI

.ci/generate_env_windows.bat, tox.ini
More information about tox: https://tox.wiki/en/latest/config.html#conf-install_command
fixes #392
=> Execute retry for pip install on Windows

hooks/conan-center.py
=> - skip symbolic links in size calculation

hooks/conan-center.py
=> - remove an annoying warning

hooks/conan-center.py
KB-H054 and KB-H071
unblocks conan-io/conan-center-index#10795
=> ignore global cpp_info when there are components

hooks/conan-center.py
See PR https://github.com/conan-io/conan-center-index/pull/11251
=> Skip googleapis from arch matching

hooks/conan-center.py, tests/test_hooks/conan-center/test_cmake_bad_files.py
it clutters a lot of PRS this way: https://github.com/conan-io/conan-center-index/pull/11374#issuecomment-1166503564
=> KB-H019: ignore files listed in build_modules

hooks/conan-center.py
From result at https://github.com/conan-io/conan-center-index/pull/11660
Related to https://github.com/conan-io/hooks/issues/268
=> [patching] Add allowed fields to patches in conandata.yml

hooks/conan-center.py
see https://github.com/conan-io/conan-center-index/pull/11864
=> - handle non-dictionary components gracefully

hooks/conan-center.py, tests/test_hooks/test_yaml_linter.py
~Check that checksum string is not empty: https://github.com/conan-io/conan/issues/11843~ (check was already implemented)
Just fix a typo in tests
=> yaml_linter - fix typo in tests

hooks/conan-center.py
Related to https://github.com/conan-io/conan-center-index/pull/12171
/cc @planetmarshall
=> Glib can be shared by default

hooks/conan-center.py
Fixes https://github.com/conan-io/conan-center-index/pull/12165
=> [conan-center] Skip GCC when checking default layout

.ci/Jenkinsfile, .ci/generate_env_macos.sh, .ci/run_tox.sh
We recently changed our macos agents in Jenkins, so this needs to be updated to fix the CI
=> [ci] Update Macos agent label to M1Macos

hooks/conan-center.py, tests/test_hooks/conan-center/test_apple_relocatable.py
Some PRs are failing due the new rule and it may affect master branch as well, forcing users to fix things which are not related to their changes.
=> [conan-center] Update KB-H077 to warning level

hooks/conan-center.py
Usually for MinGW, filename of import lib is `libfoo.dll.a`. When a recipe set `cpp_info.libs = ["foo"]`, this hook raises for MinGW shared builds.
The reason is that this hooks relies on `collect_libs()` to populate a reference array, so it will append `foo.dll` to this ref array and afterwards tests that `cpp_info.libs` matches exactly this value (which is a valid value), but it should also test against `foo` flavor since it's also a valid lib name to pass to MinGW linker.
=> KB-H054: fix MinGW shared

hooks/hook_conan-center-v2.py
=> conan v2 hooks: fix self.run usage

hooks/conan-center.py
It should be hook number 14 (layout), not 13 (artifacts location). 🤦
=> [hotfix] Fix tz package location

hooks/conan-center.py, tests/test_hooks/test_recipe_linter.py
Pinging @klausholstjacobsen
@uilianries you might want to update your PR with this change too :)
For https://github.com/conan-io/conan-center-index/pull/19031
=> Skip patch check in openssh

hooks/conan-center.py
Related to https://github.com/conan-io/conan-center-index/pull/19031 
And https://github.com/conan-io/conan-center-index/pull/19529
cc @fpelliccioni
=> Allow patch_os in gmp

hooks/conan-center.py
Related PRs:
https://github.com/conan-io/conan-center-index/pull/19031
https://github.com/conan-io/hooks/pull/518
=> KB-H030 needs to handle more cases

hooks/conan-center.py
For https://github.com/conan-io/conan-center-index/pull/18982
=> Add exception for depot_tools

hooks/conan-center.py, tests/test_hooks/conan-center/test_conan-center.py
I can't run the tests locally, so using the CI for it :)
=> Add dangling patch checks

hooks/conan-center.py
allows progress on https://github.com/conan-io/conan-center-index/issues/23660
=> KB-013: put qt in the allowlist

hooks/conan-center.py
Add allowed_list in H039 there are an error with `openjdk` in conan-center-index
=> Add allowed_list in H039

hooks/conan-center.py
Related to https://github.com/conan-io/conan-center-index/pull/24506#issuecomment-2380041494
=> add openusd in whitelist for standard libs directory
